### ISSUE TITLE
Is p2p lending in scope of this list?

### ISSUE THREAD

**Issue by marclaporte** [sebhtml/do-it-yourself-investing-in-canada#9]
https://www.lendingloop.ca/about

**Comment by sebhtml** [comment]
The web site says: "Lending Loop is Canada's first fully regulated peer-to-peer lending platform focused on small businesses."

The list is more about investing for individuals.
But I understand that one could lend money to a small business using lendingloop. Is that correct ?

**Comment by marclaporte** [comment]
Yes, and small amounts

What is the minimum amount of money I can deposit to fund my account?
$200 is the minimum amount required to initially fund your Lending Loop account. Once your account is active, you may make deposits of any amount exceeding $50 and any withdrawal exceeding $50.
https://support.lendingloop.ca/article/70-what-is-the-minimum-amount-of-money-i-can-deposit-to-fund-my-account

**Comment by marclaporte** [comment]
What is the minimum commitment I can make towards a loan?
The minimum commitment a Lender can make towards a loan is $25 and all notes are sold in $25 increments. 
https://support.lendingloop.ca/article/79-what-is-the-minimum-commitment-i-can-make-towards-a-loan

**Comment by sebhtml** [comment]
I closed this too soon.

I think that fixed income ETFs such that ZAG (BMO), XBB (BlackRock), VAB (Vanguard), DCU (Desjardins), TDB (TD), QBB (Mackenzie) are preferable to the p2p lending because they are diversified and they are admissible to registered accounts such as a TFSA account or a RRSP account.

**Comment by marclaporte** [comment]
Auto-Lend balances throughout various loan grades:
https://www.lendingloop.ca/lenders

I think P2P lending is a an interesting new category which should be promoted.
